// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FMzKdPrpIbL31URVEoD2UklLhTlCwWU',
    appId: '1:578427726418:web:f695d735ccc67ea826cd8b',
    messagingSenderId: '578427726418',
    projectId: 'redditclone-1aa0f',
    authDomain: 'redditclone-1aa0f.firebaseapp.com',
    storageBucket: 'redditclone-1aa0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmvxGJQzFk0ZqgcCHdVAY3hk0PEgKs0Vg',
    appId: '1:578427726418:android:ba89cfc407d95c5626cd8b',
    messagingSenderId: '578427726418',
    projectId: 'redditclone-1aa0f',
    storageBucket: 'redditclone-1aa0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK1ZJcRD_4Rhe3dA4CQ72DWxXZdL1Ngh4',
    appId: '1:578427726418:ios:7863e83c9f2dde9326cd8b',
    messagingSenderId: '578427726418',
    projectId: 'redditclone-1aa0f',
    storageBucket: 'redditclone-1aa0f.appspot.com',
    androidClientId: '578427726418-km8viqehd0a8o60pdjm552jfj79jk0h5.apps.googleusercontent.com',
    iosClientId: '578427726418-tvrjcn7fs9vg7lo4vls347lgasm1vmuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK1ZJcRD_4Rhe3dA4CQ72DWxXZdL1Ngh4',
    appId: '1:578427726418:ios:01ec4d565e60d20c26cd8b',
    messagingSenderId: '578427726418',
    projectId: 'redditclone-1aa0f',
    storageBucket: 'redditclone-1aa0f.appspot.com',
    androidClientId: '578427726418-km8viqehd0a8o60pdjm552jfj79jk0h5.apps.googleusercontent.com',
    iosClientId: '578427726418-ha6ojonumlfjl8cqpujdr9tg9sv9tlul.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
